export interface PostFrontmatter {
  slug: string;
  title: string;
  description: string;
  date: string;
  author: string;
  role?: string;
  readingMinutes?: number;
  tag?: string;
  cover?: string;
  keywords?: string[];
}

export interface Post extends PostFrontmatter {
  content: string;
}

function parseFrontmatter(raw: string): { data: Record<string, unknown>; content: string } {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) return { data: {}, content: raw };
  const data: Record<string, unknown> = {};
  for (const line of match[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!kv) continue;
    const key = kv[1];
    let value: string = kv[2].trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (value.startsWith("[") && value.endsWith("]")) {
      const inner = value.slice(1, -1).trim();
      data[key] = inner
        ? inner
            .split(",")
            .map((s) => s.trim().replace(/^["']|["']$/g, ""))
            .filter(Boolean)
        : [];
      continue;
    }
    if (/^-?\d+$/.test(value)) {
      data[key] = parseInt(value, 10);
      continue;
    }
    if (/^-?\d+\.\d+$/.test(value)) {
      data[key] = parseFloat(value);
      continue;
    }
    data[key] = value;
  }
  return { data, content: match[2] };
}

const modules = import.meta.glob("/src/content/blog/*.md", {
  query: "?raw",
  import: "default",
  eager: true,
}) as Record<string, string>;

const posts: Post[] = Object.entries(modules)
  .map(([path, raw]) => {
    const { data, content } = parseFrontmatter(raw);
    const slug =
      (data.slug as string) ||
      path
        .split("/")
        .pop()!
        .replace(/\.md$/, "");
    return {
      slug,
      title: (data.title as string) || "",
      description: (data.description as string) || "",
      date: data.date ? new Date(data.date as string).toISOString().slice(0, 10) : "",
      author: (data.author as string) || "",
      role: data.role as string | undefined,
      readingMinutes: data.readingMinutes as number | undefined,
      tag: data.tag as string | undefined,
      cover: data.cover as string | undefined,
      keywords: data.keywords as string[] | undefined,
      content,
    };
  })
  .sort((a, b) => (a.date < b.date ? 1 : -1));

export function getAllPosts(): Post[] {
  return posts;
}

export function getPostBySlug(slug: string): Post | undefined {
  return posts.find((p) => p.slug === slug);
}

/**
 * Blog covers are authored at full detail-page size (1600w). Homepage/blog
 * teaser cards only render them in a small box, so use the 640w variant
 * generated by scripts/optimize-images.mjs instead. Falls back to the
 * original for svg placeholders (no generated variant, already tiny).
 */
export function previewCover(cover?: string): string | undefined {
  const match = cover?.match(/^(.*)\.(webp|jpg|jpeg|png)$/i);
  if (!match) return cover;
  return `${match[1]}-preview.webp`;
}

export function formatPostDate(iso: string): string {
  if (!iso) return "";
  const d = new Date(iso);
  return d.toLocaleDateString("nb-NO", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}
