// Metadata only — no article body. Every consumer of this module (homepage
// blog teaser, blog listing, sitewide search corpus) only ever needs
// frontmatter fields, but the full ~560KB of combined article text used to
// ride along anyway because a single eager `import.meta.glob(..., {raw})`
// inlines each file's entire contents into whichever chunk imports it — and
// this module is reachable eagerly from the homepage (BlogPreviewSection)
// and the sitewide search (Navbar -> search/corpus.ts). `virtual:blog-meta`
// (see vite.config.ts) extracts just the frontmatter at build time in Node,
// so only that stays in the browser bundle. The one page that needs the full
// body — the article itself — reads it from @/lib/postContent instead,
// which only BlogPost.tsx imports, so that content lives in BlogPost's own
// lazy-loaded chunk.
import blogMeta from "virtual:blog-meta";
import type { BlogFrontmatter } from "./blogFrontmatter";

export type PostFrontmatter = BlogFrontmatter;
export type Post = BlogFrontmatter;

const posts: Post[] = [...blogMeta].sort((a, b) => (a.date < b.date ? 1 : -1));

export function getAllPosts(): Post[] {
  return posts;
}

/**
 * Blog covers are authored at full detail-page size (1600w). Homepage/blog
 * teaser cards only render them in a small box, so use the 640w variant
 * generated by scripts/optimize-images.mjs instead. Falls back to the
 * original for svg placeholders (no generated variant, already tiny).
 */
export function previewCover(cover?: string): string | undefined {
  const match = cover?.match(/^(.*)\.(webp|jpg|jpeg|png)$/i);
  if (!match) return cover;
  return `${match[1]}-preview.webp`;
}

export function formatPostDate(iso: string): string {
  if (!iso) return "";
  const d = new Date(iso);
  return d.toLocaleDateString("nb-NO", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}
