/**
 * Turns an actionable verdict into a Linear issue written as a runnable Claude
 * `/loop` goal, and files it into the improvements project (deduped).
 */
import type { LinearClient, LinearIssue } from "../../content-agent/src/linear";
import type { Verdict } from "./analyze";
import { REPOS, type Item } from "./inputs";

const norm = (s: string) => s.toLowerCase().replace(/[^a-zæøå0-9 ]/gi, "").replace(/\s+/g, " ").trim();

/** Map the agent's P-priority to Linear's native priority field. */
export function linearPriority(p: Verdict["priority"]): number {
  return { P0: 1, P1: 2, P2: 3, P3: 4 }[p] ?? 3;
}

export function goalMarkdown(item: Item, verdict: Verdict, codeSha: string): string {
  const repo = REPOS[item.target_repo];
  const evidence = verdict.code_evidence.length
    ? verdict.code_evidence.map((e) => `- \`${e.ref}\` — ${e.note}`).join("\n")
    : "- (no direct code match; see details)";
  const source =
    item.kind === "idea"
      ? `Product idea (${item.source_ref}), from search demand`
      : `Scan finding: ${item.category}/${item.severity}${item.url ? ` — ${item.url}` : ""}`;
  return [
    `**Classification:** ${verdict.type} · severity ${verdict.severity} · priority ${verdict.priority}`,
    ``,
    `## Goal`,
    verdict.fix || item.title,
    ``,
    `## Source`,
    source,
    ``,
    `## Code analysis (evidence, ${item.target_repo} @ ${codeSha.slice(0, 8)})`,
    `Status: **${verdict.status}** (confidence ${(verdict.confidence * 100).toFixed(0)} %)`,
    evidence,
    ``,
    `## Acceptance criteria`,
    `- [ ] ${verdict.fix || "Implement as described in the goal"}`,
    `- [ ] Tests and build green`,
    `- [ ] No regression in existing functionality`,
    ``,
    `## Run as a Claude loop (in \`${repo.path}\`, on a new branch)`,
    "```",
    `/loop ${verdict.goal_prompt || item.title}`,
    "```",
    ``,
    `---`,
    `_Auto-generated by the Digilist Improvements Agent from ${item.source_ref} + code analysis (graph @ ${codeSha.slice(0, 8)}). Move to the approval state to prepare an implementation branch._`,
  ].join("\n");
}

export async function fileGoal(
  client: LinearClient,
  ctx: {
    teamId: string;
    projectId: string;
    existingTitles: Set<string>;
    labelMap?: Record<string, string>;
  },
  item: Item,
  verdict: Verdict,
  codeSha: string,
): Promise<LinearIssue | null> {
  const title = item.title.length > 120 ? `${item.title.slice(0, 117)}…` : item.title;
  if (ctx.existingTitles.has(norm(title))) return null; // deduped
  // type + severity as labels (native priority carries priority).
  const labelIds = [verdict.type, verdict.severity]
    .map((n) => ctx.labelMap?.[n])
    .filter((x): x is string => Boolean(x));
  const issue = await client.createIssue({
    teamId: ctx.teamId,
    projectId: ctx.projectId,
    title,
    description: goalMarkdown(item, verdict, codeSha),
    priority: linearPriority(verdict.priority),
    labelIds: labelIds.length ? labelIds : undefined,
  });
  ctx.existingTitles.add(norm(title));
  return issue;
}

/** The categorization labels the agent maintains (name → Linear color). */
export const CATEGORY_LABELS: { name: string; color: string }[] = [
  { name: "bug", color: "#e11d48" },
  { name: "feature", color: "#3b82f6" },
  { name: "improvement", color: "#8b5cf6" },
  { name: "nice-to-have", color: "#94a3b8" },
  { name: "critical", color: "#b91c1c" },
  { name: "major", color: "#f59e0b" },
  { name: "minor", color: "#64748b" },
];
